### ISSUE TITLE
Moved to the https buttons stopped displaying.

### ISSUE THREAD

**Issue by mitulka** [sapegin/social-likes#201]
Translated the site gorshochek.by to the https protocol, the buttons are no longer displayed. What to correct?

Http://gorshochek.by/

Https://gorshochek.by/

**ISSUES IN ANY LANGUAGE EXCEPT ENGLISH WILL BE CLOSED**

**PROJECT IS NOT ACTIVELY MAINTAINED**

Which means no support, no new features and no bug fixes. I will not receive a notification about this issue.

If you want something, send a pull request and mention [sapegin](https://github.com/sapegin). If you want to maintain the project, please contact me: http://sapegin.me/

Consider using the Social Likes Next instead: http://social-likes-next.js.org/

Learn how to submit your first pull request: http://makeapullrequest.com/

**Comment by hudsondonovan** [comment]
Im just watching this project - im not maintaining the project.. 

but having a second set of eyes looking at your issue. 

The first think i see that could be the cause of your issue is that one of your jQuery scripts isnt loading over https and this is most likely the reason why other scripts on the page (including social likes) isnt loading.

**Comment by sapegin** [comment]
> Uncaught ReferenceError: jQuery is not defined
